baseURL = "https://breadtube.tv/"
languageCode = "en-us"
title = "BreadTube.tv"

[ params ]
description = "YouTube but actually good"
targetBlank = true
defaultTags = []

# https://fontawesome.com/v4.7.0/cheatsheet/
[[ params.nav ]]
name = "Reddit"
href = "https://reddit.com/r/breadtube"
icon = "reddit"

[[ params.nav ]]
name = "Discord"
href = "https://discord.gg/5MGeFv9"
icon = "discord"

[[ params.nav ]]
name = "Twitter"
href = "https://twitter.com/breadtubetv"
icon = "twitter"

[[ params.nav ]]
name = "Facebook"
href = "https://www.facebook.com/BreadTubeTV/"
icon = "facebook"

[[ params.nav ]]
name = "Tumblr"
href = "https://breadtubetv.tumblr.com/"
icon = "tumblr"

[[ params.nav ]]
name = "Github"
href = "https://github.com/breadtubetv/breadtubetv"
icon = "github"

[[ menu.main ]]
name = "Channels"
url = "/"

[[ menu.main ]]
name = "Playlists"
url = "/playlists/"

[[ menu.main ]]
name = "Contribute"
identifier = "contribute"
url = "/contribute/"

[[menu.main]]
name = "Add Playlist"
parent = "contribute"
identifier = "addplaylist"
url = "/contribute/add-playlist/"

[[menu.main]]
name = "Add Channel"
parent = "contribute"
identifier = "addchannel"
url = "/contribute/add-channel/"