baseURL = "https://breadtube.tv/"
languageCode = "en-us"
title = "BreadTube.tv"

[ params ]
description = "YouTube but actually good"
targetBlank = true
defaultTags = []

# https://fontawesome.com/v4.7.0/cheatsheet/
[[ params.nav ]]
name = "Reddit"
href = "/reddit"
icon = "reddit"

[[ params.nav ]]
name = "Discord"
href = "/discord"
icon = "discord"

[[ params.nav ]]
name = "Twitter"
href = "/twitter"
icon = "twitter"

[[ params.nav ]]
name = "Facebook"
href = "/facebook"
icon = "facebook"

[[ params.nav ]]
name = "Tumblr"
href = "/tumblr"
icon = "tumblr"

[[ params.nav ]]
name = "YouTube"
href = "/youtube"
icon = "youtube"

[[ params.nav ]]
name = "Github"
href = "/github"
icon = "github"

[[ menu.main ]]
name = "Channels"
url = "/"

[[ menu.main ]]
name = "Playlists"
url = "/playlists/"

[[ menu.main ]]
name = "Contribute"
identifier = "contribute"
url = "/contribute/"

[[ menu.main ]]
name = "Add Playlist"
parent = "contribute"
identifier = "addplaylist"
url = "/playlists/new/"

[[ menu.main ]]
name = "Add Channel"
parent = "contribute"
identifier = "addchannel"
url = "/channels/new/"