[build]
  publish = "dist"

[build.environment]
  HUGO_VERSION = "0.55.6"
  NODE_VERSION = "12.1.0"
  YARN_VERSION = "1.16.0"
  NPM_VERSION = "6.4.1"
  HUGO_ENV = "staging"

[context.production]
  command = "npm run build"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "npm run build:preview"

[context.branch-deploy]
  command = "npm run build:preview"
