---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: content/about
  label: About
  create: all
  match: "**/*"
- type: directory
  path: content/videos
  label: Videos
  create: all
  match: "**/*"
- type: directory
  path: content/privacy
  label: Privacy
  create: all
  match: "**/*"
- type: directory
  path: content/tags
  label: Tags
  create: all
  match: "**/*"
- type: directory
  path: content/channels
  label: Channels
  create: all
  match: "**/*"
- type: directory
  path: content/playlists
  label: Playlists
  create: all
  match: "**/*"
- type: directory
  path: content/channel
  label: Channel
  create: all
  match: "**/*"
- type: directory
  path: content/blog
  label: Blog
  create: all
  match: "**/*"
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.57.1
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.57.1
